### ISSUE TITLE
Order of nested evaluation on downstream branches of conditionals

### ISSUE THREAD

**Issue by ryansolid** [VSjolund/vs-bind#1]
I found this by following https://github.com/adamhaile/S/issues/26. I tend to agree with the use case. I am generally just looking for a way to handle conditional notification on computations. I hit an issue with conditionals so attempted 4 different ways(nested roots, breaking synchronicity, S.track, and S.subclock) to address it and so far only subclocks works right, but your track mechanism seems close. I'm unsure if it's a bug or expected behaviour of S.track. I'm going to use S.js syntax here but I believe you can follow. The issue is that a nested computation that should no longer matter (a soon to be disposed branch) evaluates before the parent causing an error.

```js
S.root(() => {
  const data = S.data(null),
    trigger = S.data(false),
    cache = S.track(() => !!trigger()),
    child = data => {
      S(() => console.log("nested", data().length));
      return "Hi";
    };
  const memo = S(() => (cache() ? child(data) : undefined));
  S(() => console.log("view", memo()));
  S.freeze(() => {
    trigger(true);
    data("name");
  });
  S.freeze(() => {
    data(undefined);
    trigger(false);
  });
});
```
I made trigger boolean but pretend it's a conditional that I don't want to notify when the returned boolean doesn't change. Notice I reversed the order of trigger and data setters in the last freeze. This is intentional. If I put them in the other order (trigger before data) it works fine. But I think it is too easy for some consumer of a component etc to not realize this so I think both orders should work. (I also use proxy objects often and it isn't always intuitive the order of the object properties should matter, knowing that the update is under a freeze).

What ends up happening is the initial set goes great. But on the second freeze upon evaluation it gets to ` S(() => console.log("nested", data().length));` even though that branch should no longer exist. This causes a cannot get length of undefined.

Is this a bug? Is this something S.track can accomodate?

**Comment by VSjolund** [comment]
Closing this in favor of the discussion here https://github.com/adamhaile/S/issues/32
